### ISSUE TITLE
PHP Requirement

### ISSUE THREAD

**Issue by DePalmo** [VincentMarmiesse/magento2-remove-home-from-sitemap#1]
When trying to install your module, a PHP requirement error is thrown back.

> [InvalidArgumentException]
>   Package ph2m/remove-home-from-sitemap at version  has a PHP requirement incompatible with your PHP version (7.1.16)

Please update the requirement or remove it.

**Comment by VincentMarmiesse** [comment]
Hi,
It should be fixed with version 1.0.1, can you try again and let me know?

**Comment by DePalmo** [comment]
Working, thank you!
